### ISSUE TITLE
Android 11 

### ISSUE THREAD

**Issue by xarmatura** [jawadsahil/pdf_viewer_jk#23]
```
W/System.err(19682): java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.app.Activity.getResources()' on a null object reference
W/System.err(19682): 	at pro.jawad.pdf_viewer_jk.PdfViewerJkPlugin.getPage(PdfViewerJkPlugin.java:168)
W/System.err(19682): 	at pro.jawad.pdf_viewer_jk.PdfViewerJkPlugin.access$100(PdfViewerJkPlugin.java:29)
W/System.err(19682): 	at pro.jawad.pdf_viewer_jk.PdfViewerJkPlugin$1.run(PdfViewerJkPlugin.java:70)
W/System.err(19682): 	at android.os.Handler.handleCallback(Handler.java:938)
W/System.err(19682): 	at android.os.Handler.dispatchMessage(Handler.java:99)
W/System.err(19682): 	at android.os.Looper.loop(Looper.java:223)
W/System.err(19682): 	at android.os.HandlerThread.run(HandlerThread.java:67)
I/flutter (19682): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (19682): The following _CastError was thrown building NotificationListener<KeepAliveNotification>:
I/flutter (19682): Null check operator used on a null value
I/flutter (19682): 
I/flutter (19682): The relevant error-causing widget was:
I/flutter (19682):   PDFViewer
I/flutter (19682):   file:///C:/Users/AndroidStudioProjects/byganet-flutter-app/lib/screens/pdf_viewer/pdf_viewer_screen.dart:66:17
I/flutter (19682): 
I/flutter (19682): When the exception was thrown, this was the stack:
I/flutter (19682): #0      _PDFPageState._repaint (package:pdf_viewer_jk/src/page.dart:48:45)
I/flutter (19682): #1      _PDFPageState.didChangeDependencies (package:pdf_viewer_jk/src/page.dart:36:5)
I/flutter (19682): #2      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4732:11)
I/flutter (19682): #3      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4548:5)
I/flutter (19682): #4      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3611:14)
I/flutter (19682): #5      Element.updateChild (package:flutter/src/widgets/framework.dart:3360:20)
I/flutter (19682): #6      SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6090:14)
I/flutter (19682): #7      Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
I/flutter (19682): #8      SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6090:14)
I/flutter (19682): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
I/flutter (19682): #10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4599:16)
I/flutter (19682): #11     Element.rebuild (package:flutter/src/widgets/framework.dart:4267:5)
I/flutter (19682): #12     StatelessElement.update (package:flutter/src/widgets/framework.dart:4655:5)
I/flutter (19682): #13     Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
I/flutter (19682): #14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4599:16)
I/flutter (19682): #15     Element.rebuild (package:flutter/src/widgets/framework.dart:4267:5)
I/flutter (19682): #16     ProxyElement.update (package:flutter/src/widgets/framework.dart:4922:5)
I/flutter (19682): #17     Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
I/flutter (19682): #18     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4599:16)
I/flutter (19682): #19     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4746:11)
I/flutter (19682): #20     Element.rebuild (package:flutter/src/widgets/framework.dart:4267:5)
I/flutter (19682): #21     StatefulElement.update (package:flutter/src/widgets/framework.dart:4778:5)
I/flutter (19682): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
I/flutter (19682): #23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4599:16)
I/flutter (19682): #24     Element.rebuild (package:flutter/src/widgets/framework.dart:4267:5)
I/flutter (19682): #25     StatelessElement.update (package:flutter/src/widgets/framework.dart:4655:5)
I/flutter (19682): #26     Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
I/flutter (19682): #27     SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:1241:37)
I/flutter (19682): #28     SliverMultiBoxAdaptorElement.performRebuild.processElement (package:flutter/src/widgets/sliver.dart:1146:35)
I/flutter (19682): #29     Iterable.forEach (dart:core/iterable.dart:257:30)
I/flutter (19682): #30     SliverMultiBoxAdaptorElement.performRebuild (package:flutter/src/widgets/sliver.dart:1190:24)
I/flutter (19682): #31     SliverMultiBoxAdaptorElement.update (package:flutter/src/widgets/sliver.dart:1124:7)
I/flutter (19682): #32     Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
I/flutter (19682): #33     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6090:14)
I/flutter (19682): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
I/flutter (19682): #35     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4599:16)
I/flutter (19682): #36     Element.rebuild (package:flutter/src/widgets/framework.dart:4267:5)
I/flutter (19682): #37     StatelessElement.update (package:flutter/src/widgets/framework.dart:4655:5)
I/flutter (19682): #38     Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
I/flutter (19682): #39     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5596:32)
I/flutter (19682): #40     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6243:17)
I/flutter (19682): #41     _ViewportElement.update (package:flutter/src/widgets/viewport.dart:228:11)
I/flutter (19682): #42     Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
I/flutter (19682): #43     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6090:14)
I/flutter (19682): #44     Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
I/flutter (19682): #45     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6090:14)
I/flutter (19682): #46     Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
I/flutter (19682): #47     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6090:14)
I/flutter (19682): #48     Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
I/flutter (19682): #49     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6090:14)
I/flutter (19682): #50     Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
I/flutter (19682): #51     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4599:16)
I/flutter (19682): #52     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4746:11)
I/flutter (19682): #53     Element.rebuild (package:flutter/src/widgets/framework.dart:4267:5)
I/flutter (19682): #54     StatefulElement.update (package:flutter/src/widgets/framework.dart:4778:5)
I/flutter (19682): #55     Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
I/flutter (19682): #56     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6090:14)
I/flutter (19682): #57     Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
I/flutter (19682): #58     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4599:16)
I/flutter (19682): #59     Element.rebuild (package:flutter/src/widgets/framework.dart:4267:5)
I/flutter (19682): #60     ProxyElement.update (package:flutter/src/widgets/framework.dart:4922:5)
I/flutter (19682): #61     Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
I/flutter (19682): #62     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6090:14)
I/flutter (19682): #63     Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
I/flutter (19682): #64     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6090:14)
I/flutter (19682): #65     Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
I/flutter (19682): #66     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6090:14)
I/flutter (19682): #67     Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
I/flutter (19682): #68     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6090:14)
I/flutter (19682): #69     Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
I/flutter (19682): #70     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4599:16)
I/flutter (19682): #71     Element.rebuild (package:flutter/src/widgets/framework.dart:4267:5)
I/flutter (19682): #72     StatelessElement.update (package:flutter/src/widgets/framework.dart:4655:5)
I/flutter (19682): #73     Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
I/flutter (19682): #74     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4599:16)
I/flutter (19682): #75     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4746:11)
I/flutter (19682): #76     Element.rebuild (package:flutter/src/widgets/framework.dart:4267:5)
I/flutter (19682): #77     StatefulElement.update (package:flutter/src/widgets/framework.dart:4778:5)
I/flutter (19682): #78     Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
I/flutter (19682): #79     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4599:16)
I/flutter (19682): #80     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4746:11)
I/flutter (19682): #81     Element.rebuild (package:flutter/src/widgets/framework.dart:4267:5)
I/flutter (19682): #82     StatefulElement.update (package:flutter/src/widgets/framework.dart:4778:5)
I/flutter (19682): #83     Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
I/flutter (19682): #84     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4599:16)
I/flutter (19682): #85     Element.rebuild (package:flutter/src/widgets/framework.dart:4267:5)
I/flutter (19682): #86     StatelessElement.update (package:flutter/src/widgets/framework.dart:4655:5)
I/flutter (19682): #87     Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
I/flutter (19682): #88     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4599:16)
I/flutter (19682): #89     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4746:11)
I/flutter (19682): #90     Element.rebuild (package:flutter/src/widgets/framework.dart:4267:5)
I/flutter (19682): #91     StatefulElement.update (package:flutter/src/widgets/framework.dart:4778:5)
I/flutter (19682): #92     Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
I/flutter (19682): #93     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5596:32)
I/flutter (19682): #94     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6243:17)
I/flutter (19682): #95     Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
I/flutter (19682): #96     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4599:16)
I/flutter (19682): #97     Element.rebuild (package:flutter/src/widgets/framework.dart:4267:5)
I/flutter (19682): #98     StatelessElement.update (package:flutter/src/widgets/framework.dart:4655:5)
I/flutter (19682): #99     Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
I/flutter (19682): #100    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4599:16)
I/flutter (19682): #101    Element.rebuild (package:flutter/src/widgets/framework.dart:4267:5)
I/flutter (19682): #102    ProxyElement.update (package:flutter/src/widgets/framework.dart:4922:5)
I/flutter (19682): #103    Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
I/flutter (19682): #104    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4599:16)
I/flutter (19682): #105    Element.rebuild (package:flutter/src/widgets/framework.dart:4267:5)
I/flutter (19682): #106    ProxyElement.update (package:flutter/src/widgets/framework.dart:4922:5)
I/flutter (19682): #107    Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
I/flutter (19682): #108    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5596:32)
I/flutter (19682): #109    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6243:17)
I/flutter (19682): #110    Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
I/flutter (19682): #111    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4599:16)
I/flutter (19682): #112    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4746:11)
I/flutter (19682): #113    Element.rebuild (package:flutter/src/widgets/framework.dart:4267:5)
I/flutter (19682): #114    StatefulElement.update (package:flutter/src/widgets/framework.dart:4778:5)
I/flutter (19682): #115    Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
I/flutter (19682): #116    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4599:16)
I/flutter (19682): #117    Element.rebuild (package:flutter/src/widgets/framework.dart:4267:5)
I/flutter (19682): #118    ProxyElement.update (package:flutter/src/widgets/framework.dart:4922:5)
I/flutter (19682): #119    Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
I/flutter (19682): #120    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4599:16)
I/flutter (19682): #121    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4746:11)
I/flutter (19682): #122    Element.rebuild (package:flutter/src/widgets/framework.dart:4267:5)
I/flutter (19682): #123    StatefulElement.update (package:flutter/src/widgets/framework.dart:4778:5)
I/flutter (19682): #124    Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
I/flutter (19682): #125    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6090:14)
I/flutter (19682): #126    Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
I/flutter (19682): #127    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4599:16)
I/flutter (19682): #128    Element.rebuild (package:flutter/src/widgets/framework.dart:4267:5)
I/flutter (19682): #129    StatelessElement.update (package:flutter/src/widgets/framework.dart:4655:5)
I/flutter (19682): #130    Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
I/flutter (19682): #131    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6090:14)
I/flutter (19682): #132    Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
I/flutter (19682): #133    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4599:16)
I/flutter (19682): #134    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4746:11)
I/flutter (19682): #135    Element.rebuild (package:flutter/src/widgets/framework.dart:4267:5)
I/flutter (19682): #136    StatefulElement.update (package:flutter/src/widgets/framework.dart:4778:5)
I/flutter (19682): #137    Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
I/flutter (19682): #138    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4599:16)
I/flutter (19682): #139    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4746:11)
W/System  (19682): A resource failed to call close. 
I/chatty  (19682): uid=10154(net.byga.bygaapp) FinalizerDaemon identical 3 lines
W/System  (19682): A resource failed to call close. 
I/flutter (19682): #140    Element.rebuild (package:flutter/src/widgets/framework.dart:4267:5)
I/flutter (19682): #141    StatefulElement.update (package:flutter/src/widgets/framework.dart:4778:5)
I/flutter (19682): #142    Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
I/flutter (19682): #143    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4599:16)
I/flutter (19682): #144    Element.rebuild (package:flutter/src/widgets/framework.dart:4267:5)
I/flutter (19682): #145    ProxyElement.update (package:flutter/src/widgets/framework.dart:4922:5)
I/flutter (19682): #146    Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
I/flutter (19682): #147    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4599:16)
I/flutter (19682): #148    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4746:11)
I/flutter (19682): #149    Element.rebuild (package:flutter/src/widgets/framework.dart:4267:5)
I/flutter (19682): #150    StatefulElement.update (package:flutter/src/widgets/framework.dart:4778:5)
I/flutter (19682): #151    Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
I/flutter (19682): #152    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4599:16)
I/flutter (19682): #153    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4746:11)
I/flutter (19682): #154    Element.rebuild (package:flutter/src/widgets/framework.dart:4267:5)
I/flutter (19682): #155    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2582:33)
I/flutter (19682): #156    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:875:21)
I/flutter (19682): #157    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:328:5)
I/flutter (19682): #158    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
I/flutter (19682): #159    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
I/flutter (19682): #160    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:998:5)
I/flutter (19682): #164    _invoke (dart:ui/hooks.dart:163:10)
I/flutter (19682): #165    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:259:5)
I/flutter (19682): #166    _drawFrame (dart:ui/hooks.dart:126:31)
I/flutter (19682): (elided 3 frames from dart:async)
I/flutter (19682): 
I/flutter (19682): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (19682): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (19682): The following assertion was thrown building SliverFillViewport:
I/flutter (19682): 'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 258 pos 16:
I/flutter (19682): 'child == null || indexOf(child) > index': is not true.
```

**Comment by xarmatura** [comment]
@jawadsahil Help, please

**Comment by jawadsahil** [comment]
Are you using the version 2.1.4?

**Comment by xarmatura** [comment]
yep

**Comment by xarmatura** [comment]
Seems to be fixed in the recent version.
